### ISSUE TITLE
"Add Images to the Dice Roller App" CodeLab contains MOMA URL 

### ISSUE THREAD

**Issue by sanchayitam** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#1]
Was working on Pathways of Android Basic -Kotllin & found "Add Images to Dice Roller App"  Codelab displays an incorrect URL.

Steps :
1) Go to "Add Images to Dice Roller App"  Codelab

 2) On page 5 of this particular CodeLab 
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%3Fhl%3Den

3)Click on  "Add Conditional Behavior for Different Dice Rolls " which opens the below link https://googledev.devsite.corp.google.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior#0

This link is Google Intranet  "MOMA". Am an ex-Google employee.

Please fix this issue.  Thanks!!

**Comment by jhansitavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
