### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by sam8211112222** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#10]
**URL of codelab**

**In which task and step of the 
codelab can this issue be found?**

**Describe the problem**

Cannot import total six dice pics in android studio.
<img width="960" alt="cannot import dice image" src="https://user-images.githubusercontent.com/74124757/115522181-77a94500-a2be-11eb-8bd6-8328286d773e.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@sam8211112222 
What happens when you click **Next**?

**Comment by osuleymanova** [comment]
@sam8211112222 
As there was no further clarification, the issue was closed.
