### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by tanuj1290** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#11]
**URL of codelab**

https://github.com/google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution/raw/master/dice_images.zip
**In which task and step of the codelab can this issue be found?**
Add the Dice images.

**Describe the problem**
The link is unable to open. so I am unable to download the Images of Dice.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@tanuj1290 
Check again, when you click on the link it should ask you to download the images (zip folder). 

![image](https://user-images.githubusercontent.com/24260141/122832545-5bb32700-d2a0-11eb-9857-1b203bfbebc7.png)
