### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by ColonelBlimp** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#13]
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#2

3. Add the dice images

The text says "This creates a new DiceImages folder", when actually it creates a 'dice_images' folder

**Comment by jhansitavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
