### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by Erkan191** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#14]
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#3

"Add images to the Dice Roller app">"Use Dice Images"

When I try to run the code, I get the error: Unresolved reference: findViewById
Why is this?!

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@Erkan191 
Please copy paste your error or provide us with the screenshot.

**Comment by Yuskovich** [comment]
Same problem.

![Screenshot from 2021-08-28 17-15-25](https://user-images.githubusercontent.com/43804573/131214636-2bc8d6b0-3948-49ce-80ec-d25166fbe5b5.png)

**Comment by Yuskovich** [comment]
Ok, is solve my problem - wrong "findViewByID" ("D" is capital) . Correct: "findViewById" ("d" isn't capital.)

**Comment by osuleymanova** [comment]
@Erkan191 
Thank you for reaching out to us. The issue  with capitalized letter "d" is fixed and will be published soon.
Please insert "findViewById". Hopefully it helps.
