### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#15]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images#3

**In which task and step of the codelab can this issue be found?**
Replace the sample avatar image

**Describe the problem**
It seems that the sentence "Once the **Design** view updates, the app looks much better!" should not be put in a code block, but it is.

**Steps to reproduce?**
Not applicable.

**Versions**
Not applicable.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
