### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by kogorou** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#16]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#0

**In which task and step of the codelab can this issue be found?**
access and change to Japanese

**Describe the problem**
typo in title 
Diice Roller -> Dice Roller
(Only Japanese)

**Steps to reproduce?**
1. access URL
2. change language to Japaese

**Versions**
in website

**Additional information**

**Comment by jhansitavva** [comment]
@jkcoolmom 
This is a localization issue.

**Comment by osuleymanova** [comment]
https://screenshot.googleplex.com/5Zj2bSNVTUjNzTq.png

**Comment by MenaAymanSedki** [comment]
Hi jtavva how are you 
![error SQL](https://user-images.githubusercontent.com/84380262/144429191-32cfc4cf-b93b-4327-91db-a40104b3f354.PNG)

What is the error in the code?

**Comment by MenaAymanSedki** [comment]
how are you
![error1](https://user-images.githubusercontent.com/84380262/146354871-fd9f69f3-1bf0-4e68-832f-3ad3eee06642.PNG)

I want to know why the error appear
