### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by rohan8660** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#17]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#3

**In which task and step of the codelab can this issue be found?**
4 USE THE DICE IMAGES

**Describe the problem**
![image](https://user-images.githubusercontent.com/40888098/122604043-f1796700-d092-11eb-9ffe-e9f0d4a364a7.png)
This text field has a scroll bar to scroll and read , its better to make it few-lined text rather than single long-lined text.

**Steps to reproduce?**
Just open the codelab task 4 , from given link and scroll down till you find that text field.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Comment by rohan8660** [comment]
Thanks @jtavva 🤠, Shall I close this issue or wait till you repair it ?
