### ISSUE TITLE
Android Basics

### ISSUE THREAD

**Issue by ComputerMaestro** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#18]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#3

**Describe the problem**

Whenever I press next button, to go to next tab in this tutorial. It doesn't start at the top of the page of the tab. For some reason, it is already scrolled down to some point.

**Comment by osuleymanova** [comment]
@ComputerMaestro 
Thank you for reaching out to us. The issue is not reproducible, probably already fixed.
