### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by DutchSammmie** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#2]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-conditional-dice-roll-behavior?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-conditional-dice-roll-behavior#3

**In which task and step of the codelab can this issue be found?**
Step 4: Use a when statement

**Describe the problem**
In the full when statement, number 4 is the lucky number and there's a branch in the when statement:
4 -> println("No luck! You rolled a 4. Try again!")

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
Thank you for reaching out to us.
The code you are referring to is in `else if` block, which will be executed only if `if()` condition fails.  
The `if` block is checking for the condition if `rollResult` is same as `luckyNumber`, so `else if` block will not be checked executed. 
This is implemented this way to give the developer the flexibility to change the `luckyNumber` with out changing the code logic. 

```
if (rollResult == luckyNumber) {
        println("You win!")
    } 
```
Hope this helps.
