### ISSUE TITLE
Android Basics: Read and update data with Room

### ISSUE THREAD

**Issue by MenaAymanSedki** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#22]
[](url)**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the [problem._]([url]([url](url)))

**Comment by MenaAymanSedki** [comment]
private fun rollDice1() {
    val dice = Dice(6)
    val diceRoll = dice.roll()
    val diceImage: ImageView = findViewById(R.id.imageView2)
    diceImage.contentDescription = diceRoll.toString()

    when (diceRoll) {
        1 -> diceImage.setImageResource(R.drawable.dice_7)
        2 -> diceImage.setImageResource(R.drawable.dice_2)
        3 -> diceImage.setImageResource(R.drawable.dice_3)
        4 -> diceImage.setImageResource(R.drawable.dice_4)
        5 -> diceImage.setImageResource(R.drawable.dice_2)
        6 -> diceImage.setImageResource(R.drawable.dice_6)
    }

**Comment by osuleymanova** [comment]
@Menaayman-and 
Thank you for reaching out to us. The issue is fixed and will be published soon.
