### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by muazhayihama** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#24]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#3

**In which task and step of the codelab can this issue be found?**
4 Add images to the Dice Roller app

**Describe the problem**
->Change the dice image when the button is clicked
The steps was not detailed enough, I found out that the outcome was different that what it should be.

**Comment by osuleymanova** [comment]
@muazhayihama 
Thank you for reaching out to us. Could you share please the screenshot of what you've got? and clarify what exactly are you expecting to get as the outcome?

**Comment by MenaAymanSedki** [comment]
Hi osuleymanova  
What is the error in the code?

- 
![error SQL](https://user-images.githubusercontent.com/84380262/144426949-646d4542-695f-43b3-9802-45764aeb1a2b.PNG)
