### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by tonemath** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#3]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images

**In which task and step of the codelab can this issue be found?**
3.6

**Describe the problem**
PNG images aren't .xml files, as the program points. Should be in MipMap?

Android Studio version:4.0.1

**Comment by jhansitavva** [comment]
@tonemath 
Thank you for reaching out to us. Can you please give us more details of the issue? 
The .png image assents should be drawable folder. This is the instruction from the codelab.  

> Click the + below Resource Manager, and select Import Drawables. 


Are you not able to compile the code?

**Comment by jhansitavva** [comment]
@tonemath 
It's been 14 days since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
