### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by sir-rob** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#37]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#3

**In which task and step of the codelab can this issue be found?**
Add Images to the Dice Roller App -> Section 4 -> Step 7

**Describe the problem**
Unable to change the constraint widget, top margin to 16. It's stuck at 0.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by chawatvish** [comment]
I get this error as well.
