### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by themohal** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#4]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#9
**In which task and step of the codelab can this issue be found?**

**Describe the problem**
while loading images i encountered out of memory error

**Steps to reproduce?**
1. Go to...
android manifest add largeheap and hardware accelerated
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.

PR for reference: https://github.com/google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution/pull/5
