### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by champ475** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#48]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#2

**In which task and step of the codelab can this issue be found?**
Add the dice images

**Describe the problem**
Not able to open the URL to download zip file for images

**Steps to reproduce?**
1. Go to...https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#2
2. Click on...Add the Dice images
3. See error...URL not working

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ghost** [comment]
Have you been able to solve the issue?

**Comment by champ475** [comment]
Yes the link is working now, and the dice images are being dowloaded as expected
