### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by ishivamhooda** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#49]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

url link for images not working

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by AndrewRowley** [comment]
Have you manage to solve the issue?
